# main.py
from logic import encrypt_text, decrypt_text


def read_file(filename):
    """
    Read the contents of a file.
    Like opening a book and reading what's inside.
    """
    with open(filename, 'r', encoding='utf-8') as f:
        return f.read()


def write_file(filename, content):
    """
    Write content into a file.
    Like copying content onto a new piece of paper.
    """
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)


def verify_files(original_file, decrypted_file):
    """
    Compare two files to check if they are exactly the same.
    Returns True = identical (success), False = different (failed)
    """
    original = read_file(original_file)
    decrypted = read_file(decrypted_file)
    return original == decrypted


def main():
    shift1 = int(input("Enter shift1: "))
    shift2 = int(input("Enter shift2: "))

    # Step 1: Read the original file
    text = read_file("raw_text.txt")

    # Step 2: Encrypt and save
    encrypted = encrypt_text(text, shift1, shift2)
    write_file("encrypted_text.txt", encrypted)
    print("Encryption complete! Saved to encrypted_text.txt")

    # Step 3: Decrypt and save
    decrypted = decrypt_text(encrypted, shift1, shift2)
    write_file("decrypted_text.txt", decrypted)
    print("Decryption complete! Saved to decrypted_text.txt")

    # Step 4: Verify
    if verify_files("raw_text.txt", "decrypted_text.txt"):
        print("Verification result: SUCCESS - Content matches perfectly!")
    else:
        print("Verification result: FAILED - Content does not match!")


if __name__ == "__main__":
    main()
```

---

## Step 6: Manual Verification Example 🧮

Let's say `shift1 = 2`, `shift2 = 3`, and the letter is `'a'`:

1. `'a'` is in the first half (a-m) ✓
2. Shift amount = `shift1 × shift2` = `2 × 3` = **6**
3. Position of `'a'` = 0, so 0 + 6 = 6
4. Letter at position 6 = **`'g'`**

Decryption: `'g'` is at position 6, 6 - 6 = 0 → **`'a'`** ✅ Successfully restored!

---

## ⚠️ Important Note

When decrypting, we are judging which half the **encrypted letter** falls in, not the original. The approach above — simply reversing the shift direction — is mathematically equivalent and works correctly.

---

## 📁 File Structure
```
Your project folder/
├── main.py               ← Main program
├── logic.py              ← Encryption/decryption logic
├── raw_text.txt          ← Original text (you create this)
├── encrypted_text.txt    ← Auto-generated by the program
└── decrypted_text.txt    ← Auto-generated by the program
